version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    target-branch: stable
    schedule:
      interval: weekly
      day: monday
      time: "02:00"
      timezone: Etc/UTC
    open-pull-requests-limit: 5
    groups:
      safe-go-updates:
        update-types:
          - minor
          - patch

  - package-ecosystem: github-actions
    directory: /
    target-branch: stable
    schedule:
      interval: weekly
      day: monday
      time: "02:20"
      timezone: Etc/UTC
    open-pull-requests-limit: 5
    groups:
      actions-minor-patch:
        update-types:
          - minor
          - patch

  - package-ecosystem: docker
    directory: /
    target-branch: stable
    schedule:
      interval: weekly
      day: monday
      time: "02:40"
      timezone: Etc/UTC
    open-pull-requests-limit: 3
