package public

import (
	"embed"
	"encoding/json"
	"errors"
	"fmt"
	"io/fs"
)

// bundledTheme carries the bundled preferred theme package (Komari Next) that the
// fresh-install path seeds into data/theme/<short>. The directory is populated by
// scripts/prepare-assets.py from bundled-themes.lock.json; because it always ships
// a README.md, the embed pattern resolves even before the asset is prepared, and a
// build without the prepared zip simply reports ErrBundledThemeMissing.
//
//go:embed all:bundledTheme
var bundledThemeFS embed.FS

// ErrBundledThemeMissing reports that this build has no prepared bundled theme.
var ErrBundledThemeMissing = errors.New("bundled preferred theme is not present in this build")

// BundledThemeProvenance mirrors web/public/bundledTheme/provenance.json, which is
// generated by scripts/prepare-assets.py from the lock file.
type BundledThemeProvenance struct {
	Repository   string `json:"repository"`
	Tag          string `json:"tag"`
	Commit       string `json:"commit"`
	Asset        string `json:"asset"`
	SHA256       string `json:"sha256"`
	ThemeShort   string `json:"theme_short"`
	ThemeVersion string `json:"theme_version"`
}

// BundledTheme returns the bundled preferred theme package bytes and its
// build-time provenance. Callers must verify the hash against the provenance
// before extracting anything.
func BundledTheme() ([]byte, BundledThemeProvenance, error) {
	var provenance BundledThemeProvenance

	zipBytes, err := fs.ReadFile(bundledThemeFS, "bundledTheme/next.zip")
	if err != nil {
		return nil, provenance, ErrBundledThemeMissing
	}

	rawProvenance, err := fs.ReadFile(bundledThemeFS, "bundledTheme/provenance.json")
	if err != nil {
		return nil, provenance, ErrBundledThemeMissing
	}
	if err := json.Unmarshal(rawProvenance, &provenance); err != nil {
		return nil, provenance, fmt.Errorf("bundled theme provenance is not valid JSON: %w", err)
	}
	if provenance.SHA256 == "" {
		return nil, provenance, errors.New("bundled theme provenance has no sha256")
	}
	return zipBytes, provenance, nil
}
