name: Cleanup Old Packages

on:
  #schedule:
  #  - cron: '0 0 * * 0'  # Run every Sunday at midnight
  # 会清理掉正常的镜像
  workflow_dispatch:      # Allow manual trigger

jobs:
  cleanup:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0

      - name: Cleanup old packages
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9.0.0
        with:
          script: |
            // 分页获取所有包版本
            const allVersions = [];
            let page = 1;
            let fetched;
            const packageName = process.env.GITHUB_REPOSITORY.split('/')[1];
            do {
              const { data: packages } = await github.rest.packages.getAllPackageVersionsForPackageOwnedByAuthenticatedUser({
                package_type: 'container',
                package_name: packageName,
                page,
                per_page: 100
              });
              fetched = packages.length;
              allVersions.push(...packages);
              page++;
            } while (fetched === 100);

            // 筛选仅有 SHA/sha256 标签或无标签的版本
            const shaOrNoTagVersions = allVersions.filter(pkg => {
              const tags = pkg.metadata.container.tags;
              return (
                (tags.length === 1 && (
                  tags[0].match(/^sha-[0-9a-f]{7}$/) ||
                  tags[0].match(/^sha256:[0-9a-f]{64}$/)
                )) ||
                tags.length === 0
              );
            });

            // 删除这些版本
            for (const version of shaOrNoTagVersions) {
              await github.rest.packages.deletePackageVersionForAuthenticatedUser({
                package_type: 'container',
                package_name: packageName,
                package_version_id: version.id
              });
              console.log(`Deleted package version ${version.id} with tags: ${version.metadata.container.tags.join(', ') || 'none'}`);
            }
